### PR TITLE
added a meme

### PR DESCRIPTION
**Pull request by ShinK8245**

### CODE REVIEW

**Review by YvngTurk — DISMISSED** [review]
45 needs to be fixed

**Comment by ShinK8245** [comment]
> 45 needs to be fixed

Gaffar, the red 45 is from origin file and duplicated 45(green) is from pushed code which means what you see is expected.

**Review by Akrrrrams — APPROVED** [review]
approved!

**Review by hlee0928 — APPROVED** [review]
LGTM

**Review by hlee0928 — APPROVED** [review]

**Comment by SlowGti** [comment]
Please resolve the conflict

**Pull request merged**
