### PR TITLE
[Awzar] Add my name

### PR DESCRIPTION
**Pull request by AwzarM**

### CODE REVIEW

**Review by Akrrrrams — APPROVED** [review]
well done!!

**Review by DylanAlifu — APPROVED** [review]
Looks GREAT!!!!!!

**Review by BaburDilshat — APPROVED** [review]
approve

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
Please remove all the extra spaces, and add your name to the bottom of the list.

**Review by Mujayt0231 — APPROVED** [review]
LGTM!

**Review by Muradil-Erkin — APPROVED** [review]

**Pull request merged**
