### PR TITLE
[Mujayit] Update-Name Added

### PR DESCRIPTION
**Pull request by Mujayt0231**

### CODE REVIEW

**Review by Jack-Vu — APPROVED** [review]
LGTM!

**Review by AwzarM — COMMENTED** [review]
LGTM.

**Review by DylanAlifu — APPROVED** [review]
looks GREAT!!!!!!

**Review by BaburDilshat — APPROVED** [review]
approved

**Review by Jack-Vu — APPROVED** [review]

**Review by Jack-Vu — APPROVED** [review]
LGTM!

**Review by SlowGti — COMMENTED** [review]
LGTM

**Review by Muradil-Erkin — APPROVED** [review]

**Pull request merged**
